### ISSUE TITLE
Finding WoW

### ISSUE THREAD

**Issue by bankmasta** [SingularityMods/singularity-core#1] opened 2020-11-20 19:33 UTC
When I press Scan for game or Find Game Manually I get this error:

![error](https://user-images.githubusercontent.com/10901706/99842173-a2586b80-2b6f-11eb-807c-452898e11d1d.png)

**Comment by ekinnee** [comment] 2020-11-20 19:36
Just tried the app for the first time and getting the same error.

**Comment by mlalibs** [comment] 2020-11-20 20:06
Fixed in v1.0.1! Just finished pushing the update to the auto-update server.

**Comment by dotCID** [comment] 2020-11-21 12:25
Currently occured with a fresh exe from 1.0.2 (from here: https://github.com/SingularityMods/singularity-core/releases/download/v1.0.2/Singularity-Setup.exe )
OS: Windows 10 v2004

Only changed thing from OP's screenshot seems the line number of the compiled version, which of course makes sense. 
![image](https://user-images.githubusercontent.com/3923708/99877260-11c86c80-2bfd-11eb-85df-e54306c00153.png)

**Comment by mlalibs** [comment] 2020-11-21 17:40
Sorry about that! Pushing 1.0.3 right now with the fix. I found how these both made it through my tests and fixed that too.

**Comment by dotCID** [comment] 2020-11-21 17:59
Thanks! I can't verify as uninstalling and reinstalling prompts it to instantly find the game again (probably because /AppData/ is not cleaned). As a former software tester, I can recommend breaking something you've just written a test for - this verifies the test works as intended, which quite often isn't the case : )

**Closed** 2020-11-25 20:36 UTC
Labels: bug
